# Generated by Django 3.2.6 on 2021-08-15 23:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_X00152022', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloffers',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2021, 8, 22, 23, 24, 20, 669294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaloffers',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 23, 24, 20, 669294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaloffers',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 23, 24, 20, 666280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalrewardpoints',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalrewardpoints',
            name='total_points_earned',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalrewardpoints',
            name='total_points_given',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalrewardpoints',
            name='total_points_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalstore',
            name='rp_euro_ratio',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2021, 8, 22, 23, 24, 20, 669294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 23, 24, 20, 669294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 23, 24, 20, 666280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rewardpoints',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rewardpoints',
            name='total_points_earned',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rewardpoints',
            name='total_points_given',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rewardpoints',
            name='total_points_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='rp_euro_ratio',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
    ]
