# Generated by Django 3.2.6 on 2021-08-16 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_X00152022', '0003_auto_20210816_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloffers',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2021, 8, 23, 19, 27, 17, 44368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaloffers',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 19, 27, 17, 44368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 19, 27, 17, 41375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2021, 8, 23, 19, 27, 17, 44368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 19, 27, 17, 44368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 19, 27, 17, 41375, tzinfo=utc)),
        ),
    ]
