# Generated by Django 3.2.6 on 2021-08-20 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Loyalty_X00152022', '0005_auto_20210820_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloffers',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2021, 8, 27, 14, 30, 9, 463672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicaloffers',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 14, 30, 9, 463672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 14, 30, 9, 460679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2021, 8, 27, 14, 30, 9, 463672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 14, 30, 9, 463672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 14, 30, 9, 460679, tzinfo=utc)),
        ),
    ]
